export enum OrderStatus {
  CREATED = 'CREATED',
  INVOICED = 'INVOICED',
  RECEIVED_AT_ORIGIN_WAREHOUSE = 'RECEIVED_AT_ORIGIN_WAREHOUSE',
  IN_CONTAINER = 'IN_CONTAINER',
  SENT = 'SENT',
  ARRIVED = 'ARRIVED',
  CLEARED_BY_CUSTOMS = 'CLEARED_BY_CUSTOMS',
  IN_DELIVERY_WAREHOUSE = 'IN_DELIVERY_WAREHOUSE',
  READY_TO_SEND = 'READY_TO_SEND',
  IN_DELIVERY_ROUTE = 'IN_DELIVERY_ROUTE',
  DELIVERED = 'DELIVERED',
}
